dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-odroidc2.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-p200.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-p201.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-vega-s95-pro.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-vega-s95-meta.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-vega-s95-telos.dtb

dtb-$(CONFIG_SONOS) += dhuez.dtb dhuez_v0.dtb dhuez_v1.dtb dhuez_v2.dtb dhuez_v3.dtb
dtb-$(CONFIG_SONOS) += tupelo_v4.dtb tupelo_v3.dtb tupelo_v2.dtb tupelo_v1.dtb tupelo_v0.dtb
dtb-$(CONFIG_SONOS) += goldeneye_v1.dtb goldeneye_v0.dtb
dtb-$(CONFIG_SONOS) += apollo_v0.dtb apollo_v1.dtb apollo_v2.dtb apollo_v3.dtb apollo_v4.dtb apollo_v5.dtb apollo_v6.dtb apollo_v7.dtb apollo_v8.dtb
dtb-$(CONFIG_SONOS) += apollox_v0.dtb apollox_v1.dtb apollox_v2.dtb apollox_v3.dtb apollox_v4.dtb apollox_v5.dtb
dtb-$(CONFIG_SONOS) += monaco_v5_ti_max.dtb monaco_v5_int_max.dtb monaco_v5_adi_max.dtb monaco_v5_ti_ti.dtb monaco_v5_int_ti.dtb monaco_v5_adi_ti.dtb monaco_v4.dtb monaco_v3.dtb monaco_v2.dtb monaco_v1.dtb monaco_v0.dtb
dtb-$(CONFIG_SONOS) += monacosl_v2_ti_max.dtb monacosl_v2_inf_max.dtb monacosl_v2_adi_max.dtb monacosl_v2_ti_ti.dtb monacosl_v2_inf_ti.dtb monacosl_v2_adi_ti.dtb monacosl_v1.dtb monacosl_v0.dtb
dtb-$(CONFIG_SONOS) += fury_v5.dtb fury_v4.dtb fury_v3.dtb fury_v2.dtb fury_v1.dtb fury_v0.dtb






always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
