dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-odroidc2.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-p200.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-p201.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-vega-s95-pro.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-vega-s95-meta.dtb
dtb-$(CONFIG_ARCH_MESON) += meson-gxbb-vega-s95-telos.dtb








dtb-$(CONFIG_SONOS) += optimo1_r18.dtb optimo1_v0.dtb optimo1_v1.dtb optimo1_v2.dtb optimo1_v3.dtb optimo1_v4.dtb
dtb-$(CONFIG_SONOS) += optimo1sl_v0.dtb optimo1sl_v1.dtb
dtb-$(CONFIG_SONOS) += optimo2_v0.dtb optimo2_v1.dtb optimo2_v2.dtb optimo2_v3.dtb optimo2_v4.dtb optimo2_v5.dtb




always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
